-- PipelineInsights checkpoint 2: shared core entities.
-- One matches row represents one player in one match, not the whole match.

CREATE TABLE IF NOT EXISTS pipelineinsights_schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
    player_id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    tour TEXT,
    hand TEXT,
    birth_date DATE,
    country TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
    match_id TEXT NOT NULL,
    event_date DATE NOT NULL,
    tournament TEXT NOT NULL,
    surface TEXT,
    round TEXT,
    player_id TEXT NOT NULL REFERENCES players (player_id),
    opponent_id TEXT REFERENCES players (player_id),
    is_winner BOOLEAN NOT NULL,
    games_won INTEGER,
    sets_won INTEGER,
    aces INTEGER,
    double_faults INTEGER,
    minutes INTEGER,
    PRIMARY KEY (match_id, player_id)
);

CREATE TABLE IF NOT EXISTS odds (
    odds_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id TEXT NOT NULL,
    player_id TEXT NOT NULL,
    book TEXT NOT NULL,
    prop_type TEXT NOT NULL,
    line NUMERIC(12, 3) NOT NULL,
    over_price NUMERIC(12, 3),
    under_price NUMERIC(12, 3),
    captured_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT odds_match_player_fk
        FOREIGN KEY (match_id, player_id)
        REFERENCES matches (match_id, player_id)
);

-- Empty for tennis today; retained so MLB/NFL can add availability context later.
CREATE TABLE IF NOT EXISTS injuries (
    injury_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport TEXT NOT NULL,
    player_id TEXT NOT NULL REFERENCES players (player_id),
    event_date DATE,
    status TEXT NOT NULL,
    severity TEXT,
    source TEXT,
    notes TEXT,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS matches_event_date_idx
    ON matches (event_date);
CREATE INDEX IF NOT EXISTS matches_player_date_idx
    ON matches (player_id, event_date);
CREATE INDEX IF NOT EXISTS odds_match_player_prop_idx
    ON odds (match_id, player_id, prop_type);
CREATE INDEX IF NOT EXISTS injuries_player_date_idx
    ON injuries (player_id, event_date);

INSERT INTO pipelineinsights_schema_migrations (version)
VALUES ('001_core_tables')
ON CONFLICT (version) DO NOTHING;