-- Checkpoint 9: append-only feature importance snapshots for GBM runs.

CREATE TABLE IF NOT EXISTS model_feature_importances (
    importance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelversion TEXT NOT NULL,
    sport TEXT NOT NULL,
    stat_target TEXT NOT NULL,
    quantile NUMERIC(5, 4) NOT NULL,
    feature_name TEXT NOT NULL,
    feature_description TEXT NOT NULL,
    importance_gain NUMERIC(18, 8) NOT NULL,
    importance_split NUMERIC(18, 8) NOT NULL,
    importance_rank INTEGER NOT NULL,
    run_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS model_feature_importances_lookup_idx
    ON model_feature_importances (
        sport,
        stat_target,
        modelversion,
        run_timestamp
    );

INSERT INTO pipelineinsights_schema_migrations (version)
VALUES ('012_feature_importances')
ON CONFLICT (version) DO NOTHING;